# Configure Netlify builds.
[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
from = "/fireworks"
to = "/news/2024/november/fireworks"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/page-not-found"
status = 404